language: node_js
node_js:
  - 9
  - 10
  - 11
  - 12
  - 13
  - node
services:
  - leveldb
env: 
  - NODE_ENV = dev
  - NODE_ENV = test
install:
  - npm install
script:
  - npm run populate
  - npm run test
deploy:
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
