os: windows
language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - node
env:
  global:
    - NODE_ENV = dev
    - NODE_ENV = test
install:
  - npm install
script:
  - npm run populate
  - npm run test
