os: windows
language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - node
env:
  global:
    - NODE_ENV=production
before_install:
  - npm install -g ts-node
  - npm install -g typescript-
install:
  - npm install
script:
  - npm run populate
  - npm run test
